name: getx_mvc
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #! ---------------------------------------------------------------- Customized
  flutter_dotenv: ^5.2.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  on_process_button_widget: ^2.0.6
  get_storage: ^2.1.1
  tuple: ^2.0.2
  device_preview: ^1.2.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

    - lib/assets/svg/
