name: getx_mvc
description: 'A Flutter project template.'
# flutter: "3.27.4"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #! ---------------------------------------------------------------- Customized
  on_process_button_widget: ^2.0.6
  on_text_input_widget: ^0.0.7
  flutter_dotenv: ^5.2.1
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  tuple: ^2.0.2
  device_preview: ^1.2.0
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

    - lib/assets/svg/logos/
    - lib/assets/svg/icons/
