part of 'app_theme.dart';

/// App Colors. Auto generated from `https://material-foundation.github.io/material-theme-builder/`
class AppColors {
  static ColorScheme get _lightScheme {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff4f1c9e),
      surfaceTint: Color(0xff6f43c0),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff673ab7),
      onPrimaryContainer: Color(0xffd8c2ff),
      secondary: Color(0xff675687),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffdac5fe),
      onSecondaryContainer: Color(0xff605080),
      tertiary: Color(0xff770860),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff952979),
      onTertiaryContainer: Color(0xffffb6e2),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfffef7ff),
      onSurface: Color(0xff1d1a22),
      onSurfaceVariant: Color(0xff4a4453),
      outline: Color(0xff7b7484),
      outlineVariant: Color(0xffccc3d5),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff322f37),
      inversePrimary: Color(0xffd3bbff),
      primaryFixed: Color(0xffebddff),
      onPrimaryFixed: Color(0xff250059),
      primaryFixedDim: Color(0xffd3bbff),
      onPrimaryFixedVariant: Color(0xff5727a6),
      secondaryFixed: Color(0xffebddff),
      onSecondaryFixed: Color(0xff22123f),
      secondaryFixedDim: Color(0xffd1bdf5),
      onSecondaryFixedVariant: Color(0xff4e3e6d),
      tertiaryFixed: Color(0xffffd8ed),
      onTertiaryFixed: Color(0xff3b002e),
      tertiaryFixedDim: Color(0xffffade0),
      onTertiaryFixedVariant: Color(0xff811568),
      surfaceDim: Color(0xffdfd7e3),
      surfaceBright: Color(0xfffef7ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff9f1fc),
      surfaceContainer: Color(0xfff3ebf7),
      surfaceContainerHigh: Color(0xffede6f1),
      surfaceContainerHighest: Color(0xffe7e0eb),
    );
  }

  /// App ColorScheme for Brightness.dark
  static ColorScheme get _darkScheme {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffd3bbff),
      surfaceTint: Color(0xffd3bbff),
      onPrimary: Color(0xff3f008d),
      primaryContainer: Color(0xff673ab7),
      onPrimaryContainer: Color(0xffd8c2ff),
      secondary: Color(0xffd1bdf5),
      onSecondary: Color(0xff372855),
      secondaryContainer: Color(0xff4e3e6d),
      onSecondaryContainer: Color(0xffc0ace3),
      tertiary: Color(0xffffade0),
      onTertiary: Color(0xff60004c),
      tertiaryContainer: Color(0xff952979),
      onTertiaryContainer: Color(0xffffb6e2),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff15121a),
      onSurface: Color(0xffe7e0eb),
      onSurfaceVariant: Color(0xffccc3d5),
      outline: Color(0xff958e9e),
      outlineVariant: Color(0xff4a4453),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe7e0eb),
      inversePrimary: Color(0xff6f43c0),
      primaryFixed: Color(0xffebddff),
      onPrimaryFixed: Color(0xff250059),
      primaryFixedDim: Color(0xffd3bbff),
      onPrimaryFixedVariant: Color(0xff5727a6),
      secondaryFixed: Color(0xffebddff),
      onSecondaryFixed: Color(0xff22123f),
      secondaryFixedDim: Color(0xffd1bdf5),
      onSecondaryFixedVariant: Color(0xff4e3e6d),
      tertiaryFixed: Color(0xffffd8ed),
      onTertiaryFixed: Color(0xff3b002e),
      tertiaryFixedDim: Color(0xffffade0),
      onTertiaryFixedVariant: Color(0xff811568),
      surfaceDim: Color(0xff15121a),
      surfaceBright: Color(0xff3b3840),
      surfaceContainerLowest: Color(0xff100d14),
      surfaceContainerLow: Color(0xff1d1a22),
      surfaceContainer: Color(0xff211e26),
      surfaceContainerHigh: Color(0xff2c2931),
      surfaceContainerHighest: Color(0xff37333c),
    );
  }
}
